In [158]:
import pyforest

In [159]:
df = pd.read_csv(r'D:\Training-Phase2\Signal Miner\Scraping_raw_data\raw_data.csv')

In [160]:
df.head()

,company_name,job_title,department,location,seniority,job_url,growth_signal_tag
0,Razorpay,Manager - Channel Partnerships,Channel Partnerships,Bengaluru,Other,https://job-boards.greenhouse.io/razorpaysoftw...,NaN
1,Paytm,SAM - Senior Associate/Team Lead/Assistant Man...,Business,Chennai,Mid,https://jobs.lever.co/paytm/3834eb18-d7cd-4d61...,NaN
2,Drip Capital,Security Compliance Engineer,Technology,"Mumbai, Maharashtra, India",Other,https://dripcapital.hire.trakstar.com/jobs/fk0...,NaN
3,Paytm,Product Operation - Assistant Manager - Lending,Operations & support,Noida,Other,https://jobs.lever.co/paytm/84b23183-8313-4c50...,NaN
4,Paytm,Area Sales Manager - Midmarket Sales (EDC Retail),Sales,Bangalore,Mid,https://jobs.lever.co/paytm/596a4462-0a95-479e...,NaN

In [161]:
department_map = {
    "Channel Partnerships": "Partnerships",
    "Alliances": "Partnerships",
    "Operations & support": "Operations",
    "Support": "Operations",
    "Technology": "Tech",
    "Engineering": "Tech",
    "Sales": "Sales",
    "Inside Sales": "Sales",
    "Marketing": "Marketing",
    "Growth": "Marketing",
    "Business": "Business Development",
    "Product": "Product",
}

location_map = {
    "Bangalore": "Bangalore,India",
    "Bengaluru": "Bangalore,India",
    "Chennai": "Chennai,India",
    "Mumbai": "Mumbai,India",
    'Mumbai, Maharashtra, India':"Mumbai,India",
    "Noida": "Noida,India",
    "Delhi": "Delhi,India",
    "Delhi NCR": "Delhi NCR,India",
    "Delhi-ncr / ghaziabad": "Delhi NCR,India",
    "Gurgaon": "Gurgaon,India",
    "Hyderabad": "Hyderabad,India",
    "Bangalore South, Karnataka, India": "Bangalore,India",
    "Salt Lake City - USA, US": "Salt Lake City,US",
    "jakarta, Jakarta Raya, Indonesia": "Jakarta,Indonesia",
    "Malaysia": "Malaysia",
    "Singapore": "Singapore",
    "Remote": "Remote",
    "Goa": "Goa,India",
    "Amritsar": "Amritsar,India",
    "Ahmedabad": "Ahmedabad,India",
    "Kozhikode": "Kozhikode,India"
}


df["department"] = df["department"].map(department_map).fillna("Other")
df["location"] = df["location"].map(location_map).fillna(df["location"])

In [162]:
df.head()

,company_name,job_title,department,location,seniority,job_url,growth_signal_tag
0,Razorpay,Manager - Channel Partnerships,Partnerships,"Bangalore,India",Other,https://job-boards.greenhouse.io/razorpaysoftw...,NaN
1,Paytm,SAM - Senior Associate/Team Lead/Assistant Man...,Business Development,"Chennai,India",Mid,https://jobs.lever.co/paytm/3834eb18-d7cd-4d61...,NaN
2,Drip Capital,Security Compliance Engineer,Tech,"Mumbai,India",Other,https://dripcapital.hire.trakstar.com/jobs/fk0...,NaN
3,Paytm,Product Operation - Assistant Manager - Lending,Operations,"Noida,India",Other,https://jobs.lever.co/paytm/84b23183-8313-4c50...,NaN
4,Paytm,Area Sales Manager - Midmarket Sales (EDC Retail),Sales,"Bangalore,India",Mid,https://jobs.lever.co/paytm/596a4462-0a95-479e...,NaN

In [163]:
df.department.unique()

array(['Partnerships', 'Business Development', 'Tech', 'Operations',
       'Sales', 'Other', 'Marketing', 'Product'], dtype=object)

In [164]:
df.location.unique()

array(['Bangalore,India', 'Chennai,India', 'Mumbai,India', 'Noida,India',
       'Delhi,India', 'Malaysia', 'Hyderabad,India', 'Salt Lake City,US',
       'Delhi NCR,India', 'Jakarta,Indonesia', 'Goa,India', 'Remote',
       'Gurgaon,India', 'Amritsar,India', 'Ahmedabad,India', 'Singapore',
       'Kozhikode,India'], dtype=object)

In [165]:
df.isnull().sum()

company_name           0
job_title              0
department             0
location               0
seniority              0
job_url                0
growth_signal_tag    154
dtype: int64

In [166]:
import re

# Function to extract seniority level from job_title
def extract_seniority_from_title(title):
    title = title.lower()
    if re.search(r"\b(intern|trainee|entry level|junior)\b", title):
        return "Junior"
    elif re.search(r"\b(mid|associate|executive|assistant manager|team lead)\b", title):
        return "Mid"
    elif re.search(r"\b(senior|lead|manager)\b", title):
        return "Senior"
    elif re.search(r"\b(head|director|vp|vice president|chief|cto|ceo|coo)\b", title):
        return "Executive"
    else:
        return "Not Specified"

# Apply the extraction function to the job_title column
df["seniority"] = df["job_title"].apply(extract_seniority_from_title)
df.seniority.nunique()

5

In [167]:
df.seniority.unique()

array(['Senior', 'Mid', 'Not Specified', 'Junior', 'Executive'],
      dtype=object)

In [168]:
df.head()

,company_name,job_title,department,location,seniority,job_url,growth_signal_tag
0,Razorpay,Manager - Channel Partnerships,Partnerships,"Bangalore,India",Senior,https://job-boards.greenhouse.io/razorpaysoftw...,NaN
1,Paytm,SAM - Senior Associate/Team Lead/Assistant Man...,Business Development,"Chennai,India",Mid,https://jobs.lever.co/paytm/3834eb18-d7cd-4d61...,NaN
2,Drip Capital,Security Compliance Engineer,Tech,"Mumbai,India",Not Specified,https://dripcapital.hire.trakstar.com/jobs/fk0...,NaN
3,Paytm,Product Operation - Assistant Manager - Lending,Operations,"Noida,India",Mid,https://jobs.lever.co/paytm/84b23183-8313-4c50...,NaN
4,Paytm,Area Sales Manager - Midmarket Sales (EDC Retail),Sales,"Bangalore,India",Senior,https://jobs.lever.co/paytm/596a4462-0a95-479e...,NaN

In [169]:
len(df[df['seniority']=='Not Specified'])

45

In [170]:
df.to_csv("cleaned_data.csv",index=False)

In [171]:
def assign_growth_signal(row):
    title = str(row['job_title']).lower()
    dept = str(row['department']).lower()
    seniority = str(row['seniority']).lower()
    
    # Rule-based tagging
    if 'product' in dept or 'product manager' in title:
        return "Product Launch"
    elif any(keyword in dept for keyword in ['sales', 'business development', 'marketing']) or \
         any(keyword in title for keyword in ['growth', 'gtm', 'go-to-market']):
        return "GTM Push"
    elif 'design' in dept or any(keyword in title for keyword in ['ux', 'ui', 'designer']):
        return "Design Overhaul"
    elif any(keyword in title for keyword in ['engineer', 'developer', 'data', 'machine learning', 'security', 'infra', 'platform']):
        return "Tech Modernization"
    elif any(keyword in title for keyword in ['compliance', 'risk', 'esg', 'sustainability']):
        return "Regulatory Focus"
    elif seniority in ['entry', 'mid']:
        return "Hiring Spree"
    else:
        return "General Growth"

In [172]:
df['growth_signal_tag'] = df.apply(assign_growth_signal, axis=1)
df.head()

,company_name,job_title,department,location,seniority,job_url,growth_signal_tag
0,Razorpay,Manager - Channel Partnerships,Partnerships,"Bangalore,India",Senior,https://job-boards.greenhouse.io/razorpaysoftw...,General Growth
1,Paytm,SAM - Senior Associate/Team Lead/Assistant Man...,Business Development,"Chennai,India",Mid,https://jobs.lever.co/paytm/3834eb18-d7cd-4d61...,GTM Push
2,Drip Capital,Security Compliance Engineer,Tech,"Mumbai,India",Not Specified,https://dripcapital.hire.trakstar.com/jobs/fk0...,Tech Modernization
3,Paytm,Product Operation - Assistant Manager - Lending,Operations,"Noida,India",Mid,https://jobs.lever.co/paytm/84b23183-8313-4c50...,Hiring Spree
4,Paytm,Area Sales Manager - Midmarket Sales (EDC Retail),Sales,"Bangalore,India",Senior,https://jobs.lever.co/paytm/596a4462-0a95-479e...,GTM Push

In [173]:
df['growth_signal_tag'].value_counts()

growth_signal_tag
GTM Push              52
General Growth        41
Hiring Spree          25
Tech Modernization    23
Design Overhaul        6
Regulatory Focus       5
Product Launch         2
Name: count, dtype: int64

In [174]:
df.to_csv("tagged_data.csv",index=False)

In [175]:
df.company_name.unique()

array(['Razorpay', 'Paytm', 'Drip Capital', 'Urban Company', 'CRED',
       'Meesho', 'Chargebee', 'Yellow.ai', 'Zolve', 'Groww'], dtype=object)

In [177]:
department_counts = df.groupby(['company_name', 'department']).size().unstack(fill_value=0)
seniority_counts = df.groupby(['company_name', 'seniority']).size().unstack(fill_value=0)
job_counts = df.groupby('company_name').size().rename("total_jobs")

# Combine into one DataFrame
company_features = pd.concat([job_counts, department_counts, seniority_counts], axis=1).fillna(0)

# Ensure all expected columns exist
expected_dept_cols = ['Business Development', 'Marketing', 'Operations', 'Partnerships', 'Product', 'Sales', 'Tech', 'Other']
expected_seniority_cols = ['Executive', 'Junior', 'Mid', 'Senior', 'Not Specified']
for col in expected_dept_cols + expected_seniority_cols:
    if col not in company_features.columns:
        company_features[col] = 0

# Define tagging logic
def enriched_growth_tag(row):
    total_jobs = row['total_jobs']
    departments = row[expected_dept_cols]
    tech_roles = row['Tech']
    sales_roles = row['Sales']
    bd_roles = row['Business Development']
    marketing_roles = row['Marketing']
    diverse_depts = (departments > 0).sum()
    senior_or_mid_roles = row['Senior'] + row['Mid']

    if total_jobs > 15 and diverse_depts >= 3 and senior_or_mid_roles >= total_jobs * 0.5:
        return 'Hiring Spree'
    if (sales_roles + bd_roles + marketing_roles) >= total_jobs * 0.4:
        return 'GTM Push'
    if tech_roles >= total_jobs * 0.4:
        return 'Tech Modernization'
    if 5 <= total_jobs <= 15 and diverse_depts >= 2:
        return 'Multi-Signal Growth'
    return 'General Growth'

# Apply the tagging function
company_features['enhanced_growth_signal_tag'] = company_features.apply(enriched_growth_tag, axis=1)

# Reset index to make company_name a column
company_features = company_features.reset_index()

# View the results
company_features[['company_name', 'total_jobs', 'enhanced_growth_signal_tag']]

    company_name  total_jobs enhanced_growth_signal_tag
0           CRED           4             General Growth
1      Chargebee           3             General Growth
2   Drip Capital          18               Hiring Spree
3          Groww           4             General Growth
4         Meesho          15        Multi-Signal Growth
5          Paytm          27               Hiring Spree
6       Razorpay          42               Hiring Spree
7  Urban Company          26                   GTM Push
8      Yellow.ai           7             General Growth
9          Zolve           8        Multi-Signal Growth

In [181]:
company_features = company_features.sample(frac=1).reset_index(drop=True)
company_features

,company_name,total_jobs,Business Development,Marketing,Operations,Other,Partnerships,Product,Sales,Tech,Executive,Junior,Mid,Not Specified,Senior,enhanced_growth_signal_tag
0,Meesho,15,2,0,0,13,0,0,0,0,0,0,14,1,0,Multi-Signal Growth
1,CRED,4,0,0,0,4,0,0,0,0,0,0,0,4,0,General Growth
2,Yellow.ai,7,0,0,0,7,0,0,0,0,0,0,2,2,3,General Growth
3,Urban Company,26,26,0,0,0,0,0,0,0,0,0,0,5,21,GTM Push
4,Drip Capital,18,0,2,0,14,0,0,0,2,0,3,0,6,9,Hiring Spree
5,Razorpay,42,0,0,0,40,1,0,0,1,1,1,8,11,21,Hiring Spree
6,Paytm,27,2,2,1,10,0,1,10,1,0,1,5,11,10,Hiring Spree
7,Zolve,8,3,0,0,4,0,1,0,0,0,0,1,4,3,Multi-Signal Growth
8,Groww,4,0,1,0,2,0,0,0,1,0,1,0,1,2,General Growth
9,Chargebee,3,0,0,0,3,0,0,0,0,0,0,1,0,2,General Growth

In [182]:
company_features.to_csv("overall_growth_signals.csv",index=False)

In [183]:
company_features[['company_name', 'total_jobs', 'enhanced_growth_signal_tag']]

    company_name  total_jobs enhanced_growth_signal_tag
0         Meesho          15        Multi-Signal Growth
1           CRED           4             General Growth
2      Yellow.ai           7             General Growth
3  Urban Company          26                   GTM Push
4   Drip Capital          18               Hiring Spree
5       Razorpay          42               Hiring Spree
6          Paytm          27               Hiring Spree
7          Zolve           8        Multi-Signal Growth
8          Groww           4             General Growth
9      Chargebee           3             General Growth

In [184]:
company_features[['company_name', 'total_jobs', 'enhanced_growth_signal_tag']].to_csv("companies_and_tags.csv",index=False)